# Generated by Django 5.1.3 on 2024-12-25 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_student_alter_basemodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bcbf9c5d-3205-4826-be52-9d7d1ac55a45'), editable=False, primary_key=True, serialize=False),
        ),
    ]
